artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/0ef0943904c4480b849bab4563407aec/artifacts
end_time: 1761431650683
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 0ef0943904c4480b849bab4563407aec
run_name: Random Forest_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761431502615
status: 3
tags: []
user_id: silva
