artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/2dfa6a06031343e8ac29152bee9756b1/artifacts
end_time: 1761403072073
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 2dfa6a06031343e8ac29152bee9756b1
run_name: LightGBM_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761401652580
status: 4
tags: []
user_id: silva
