artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/edccec3d48894093b7ed287335e63702/artifacts
end_time: 1761435241724
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: edccec3d48894093b7ed287335e63702
run_name: LightGBM_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761433791760
status: 3
tags: []
user_id: silva
