[project]
name = "sair"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.13"
dependencies = []
=======
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.49.1",
    "ipywidgets>=8.1.7",
    "kaggle>=1.7.4.5",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.6",
    "mlflow>=3.5.0",
    "nbconvert>=7.16.6",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "streamlit>=1.50.0",
    "xgboost>=3.1.1",
]
>>>>>>> 3cb0f9a040ed43401978760a69a814d5a869ab9e
