artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/a5f69943193643be8df31a051bc33057/artifacts
end_time: 1761429900410
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: a5f69943193643be8df31a051bc33057
run_name: Gradient Boosting_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761429773845
status: 3
tags: []
user_id: silva
