artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/7ebe6f30a3a5425a8657cdb948c998f9/artifacts
end_time: 1761485537076
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 7ebe6f30a3a5425a8657cdb948c998f9
run_name: LightGBM
source_name: ''
source_type: 4
source_version: ''
start_time: 1761484851472
status: 3
tags: []
user_id: silva
