artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/3f67b471db5a4313b2be9ffdb69476bf/artifacts
end_time: 1761488028280
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 3f67b471db5a4313b2be9ffdb69476bf
run_name: LightGBM_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761486556324
status: 3
tags: []
user_id: silva
