artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/ec8a93e226c44228ae1a7145aec5d084/artifacts
end_time: 1761510884401
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: ec8a93e226c44228ae1a7145aec5d084
run_name: Gradient Boosting
source_name: ''
source_type: 4
source_version: ''
start_time: 1761510857089
status: 3
tags: []
user_id: silva
