artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/e23d23a63e7d43e6a6430af9cc95905e/artifacts
end_time: 1761486414842
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: e23d23a63e7d43e6a6430af9cc95905e
run_name: Random Forest_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761486253755
status: 3
tags: []
user_id: silva
