artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/ba1c9467934e44fba596a34419cd6f7b/artifacts
end_time: 1761408317281
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: ba1c9467934e44fba596a34419cd6f7b
run_name: LightGBM_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761406679393
status: 3
tags: []
user_id: silva
