artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/d6abbacc313940208aa9c38c3b2a2a8f/artifacts
end_time: 1761484851470
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: d6abbacc313940208aa9c38c3b2a2a8f
run_name: XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1761484833331
status: 3
tags: []
user_id: silva
