artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/9f59d447939944fc8598f256e8bc0ae4/artifacts
end_time: 1761399354696
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 9f59d447939944fc8598f256e8bc0ae4
run_name: Decision Tree
source_name: ''
source_type: 4
source_version: ''
start_time: 1761399349865
status: 3
tags: []
user_id: silva
