artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/d3669ca7f26e467d8386f2bda2e537e7/artifacts
end_time: 1761510904157
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: d3669ca7f26e467d8386f2bda2e537e7
run_name: K-Nearest Neighbors
source_name: ''
source_type: 4
source_version: ''
start_time: 1761510895162
status: 3
tags: []
user_id: silva
