artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/47fe7a313b524c188cd747fb8c706a48/artifacts
end_time: 1761439486349
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 47fe7a313b524c188cd747fb8c706a48
run_name: LightGBM_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761438013085
status: 3
tags: []
user_id: silva
