artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/f65a53302a124896ba4b54262826aae8/artifacts
end_time: 1761486552865
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: f65a53302a124896ba4b54262826aae8
run_name: Gradient Boosting_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761486414846
status: 3
tags: []
user_id: silva
