artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/baaf63b2ed32495cafb2b9b89bd91395/artifacts
end_time: 1761439844217
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: baaf63b2ed32495cafb2b9b89bd91395
run_name: Random Forest_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761439688417
status: 3
tags: []
user_id: silva
