artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/c62e3eab7ecc45b09926fc84d92b769a/artifacts
end_time: 1761406679388
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: c62e3eab7ecc45b09926fc84d92b769a
run_name: Logistic Regression_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761406669799
status: 3
tags: []
user_id: silva
