artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/2accf595059a427a9b6ca412619e4982/artifacts
end_time: 1761401652578
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 2accf595059a427a9b6ca412619e4982
run_name: Logistic Regression_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761401649033
status: 3
tags: []
user_id: silva
