artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/6f03832a4190484b8c0834936ced3f9f/artifacts
end_time: 1761401521054
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 6f03832a4190484b8c0834936ced3f9f
run_name: Random Forest_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761401366627
status: 3
tags: []
user_id: silva
