artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/2476a83a583744f9b2d6da280bc5eb69/artifacts
end_time: 1761484833328
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 2476a83a583744f9b2d6da280bc5eb69
run_name: Support Vector Machine
source_name: ''
source_type: 4
source_version: ''
start_time: 1761484810915
status: 3
tags: []
user_id: silva
