artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/1338d9f425eb4a9ebe8426e631b243e4/artifacts
end_time: 1761439973263
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 1338d9f425eb4a9ebe8426e631b243e4
run_name: Gradient Boosting_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761439844219
status: 3
tags: []
user_id: silva
