artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/d14e9be875224b7697a3131eb2d2960a/artifacts
end_time: 1761405132089
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: d14e9be875224b7697a3131eb2d2960a
run_name: XGBoost_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761405120376
status: 4
tags: []
user_id: silva
