artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/4a2416e8ce304c99b9ef68b86ec09768/artifacts
end_time: 1761399398254
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 4a2416e8ce304c99b9ef68b86ec09768
run_name: Support Vector Machine
source_name: ''
source_type: 4
source_version: ''
start_time: 1761399378713
status: 3
tags: []
user_id: silva
