artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/a8e89415f5b24777953e0cf70d180d1b/artifacts
end_time: 1761437540433
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: a8e89415f5b24777953e0cf70d180d1b
run_name: LightGBM_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761435989463
status: 3
tags: []
user_id: silva
