artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/908da0920b0d4f0580f9ec485322fb0c/artifacts
end_time: 1761435985822
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 908da0920b0d4f0580f9ec485322fb0c
run_name: Gradient Boosting_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761435859884
status: 3
tags: []
user_id: silva
