artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/de5bc1182551455b89d79ea6847c859d/artifacts
end_time: 1761484802068
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: de5bc1182551455b89d79ea6847c859d
run_name: Gradient Boosting
source_name: ''
source_type: 4
source_version: ''
start_time: 1761484792685
status: 3
tags: []
user_id: silva
