artifact_location: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013
creation_time: 1761399259233
experiment_id: '442528966068798013'
last_update_time: 1761399259233
lifecycle_stage: active
name: spaceship_titanic_classification
