artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/4a3f61f358434b2cb16e2b6f46cf12a6/artifacts
end_time: 1761399418085
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 4a3f61f358434b2cb16e2b6f46cf12a6
run_name: XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1761399398258
status: 3
tags: []
user_id: silva
