artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/e883e6bea26448238c5ae9c60d01f226/artifacts
end_time: 1761400093264
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: e883e6bea26448238c5ae9c60d01f226
run_name: Voting Ensemble
source_name: ''
source_type: 4
source_version: ''
start_time: 1761400081322
status: 3
tags: []
user_id: silva
