artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/bd491a2dff6549b4b6845b7d41fadc10/artifacts
end_time: 1761433237878
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: bd491a2dff6549b4b6845b7d41fadc10
run_name: LightGBM_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761431779308
status: 3
tags: []
user_id: silva
