artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/0c90fcf67b8d4054b3947b78104e24b2/artifacts
end_time: 1761438013082
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 0c90fcf67b8d4054b3947b78104e24b2
run_name: Logistic Regression_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761438009350
status: 3
tags: []
user_id: silva
