artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/262f5031eb074c30a3bd0602d0e6d51d/artifacts
end_time: 1761431779305
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 262f5031eb074c30a3bd0602d0e6d51d
run_name: Logistic Regression_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761431775724
status: 3
tags: []
user_id: silva
