artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/04ebf2e7c56a47459db79128883773c3/artifacts
end_time: 1761439976971
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 04ebf2e7c56a47459db79128883773c3
run_name: Logistic Regression_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761439973265
status: 3
tags: []
user_id: silva
