artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/509397f683904e00b23abfe968dbaa78/artifacts
end_time: 1761431775722
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 509397f683904e00b23abfe968dbaa78
run_name: Gradient Boosting_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761431650685
status: 3
tags: []
user_id: silva
