artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/ad5cf9f33fab4e538eeee2d3258c3f3e/artifacts
end_time: 1761435989460
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: ad5cf9f33fab4e538eeee2d3258c3f3e
run_name: Logistic Regression_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761435985825
status: 3
tags: []
user_id: silva
