artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/6465f63604344493b425fff2de91d6af/artifacts
end_time: 1761403570594
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 6465f63604344493b425fff2de91d6af
run_name: Random Forest_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761403416845
status: 3
tags: []
user_id: silva
