artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/b8b70a0a6c234cbc8ad34b846f7aa4c9/artifacts
end_time: 1761408331578
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: b8b70a0a6c234cbc8ad34b846f7aa4c9
run_name: XGBoost_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761408317283
status: 4
tags: []
user_id: silva
