artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/2f33b0d8fa6a47cabac556fb12b658d4/artifacts
end_time: 1761406669792
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: 2f33b0d8fa6a47cabac556fb12b658d4
run_name: Gradient Boosting_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1761406330793
status: 3
tags: []
user_id: silva
