artifact_uri: file:///home/silva/SILVA.AI/Projects/SAIR/Classification/spaceship_experiments/442528966068798013/f542f6c2ddfa478a93ee39e6d42c2799/artifacts
end_time: 1761510963250
entry_point_name: ''
experiment_id: '442528966068798013'
lifecycle_stage: active
run_id: f542f6c2ddfa478a93ee39e6d42c2799
run_name: Support Vector Machine
source_name: ''
source_type: 4
source_version: ''
start_time: 1761510904165
status: 3
tags: []
user_id: silva
